### ISSUE TITLE
Site is not loading :(

### ISSUE THREAD

**Issue by ghost** [efekoca/web-tools#2]
Hi, once again I am making a new issue, just because that issue is not fixing, I have uploaded your complete script (created the right database) in the public_html folder. And whenever accessing the website, the home page is loading, but the tools are not loading just showing me 404 error. What could be the exact solution?

Here is my site link: https://roydigitalnexus.com/

Thanks, hope you will provide me the correct solution.

**Comment by efekoca** [comment]
Hi, this is because you don't have ".htaccess" file. When you download a project as zip, ".htaccess" file doesn't download with it.

The solution is create a file with exact name ".htaccess" and add content of https://github.com/efekoca/web-tools/blob/main/.htaccess

Meanwhile, thank you for your interest!

**Comment by ghost** [comment]
Thank you for your response and clear efficient. I can't express about my
excitement and respect regarding your awesome project.

Really I have big contribution to your project I am developing something
much more about this certain project and I will pull my requests with the
upgradation very soon. Hope you will find something much better than this
current version. Have a nice day.

**Comment by efekoca** [comment]
This is so nice to hear that. I will be eagerly waiting for the result. I wish you good work!
